### PR TITLE
Improved contributing doc:

### PR DESCRIPTION
**Pull request by daonb**
- place the dependencies install before the build commands
- remove duplicated unit testing instructions

### CODE REVIEW

**Comment by JoeGermuska** [comment]
Thank you for your contribution. However, it specifies at least a few things which are a matter of taste, and which are actually counter to how everyone here at Knight Lab does things -- such as using `virtualenv` directly instead of our preference, `virtualenvwrapper`, and creating a directory for `timeline`.

I'd prefer a pull request which clarifies the overall steps without changing them, since we are most often the ones in the position of supporting new developers (students at Knight Lab) and would rather have beginners all have consistent setups.

**Comment by daonb** [comment]
Thanks for a great tool! (and here's our [page](http://test.spotlight.bh.org.il/czech) )

As for `virtualenv` vs. `virtualenvwrapper`, the current instructions use the former and it's not my place to change it.

As for the new `timeline` directory, I admit that was an addition I've made, but one that stems from the current instructions.  The current instructions direct me to install `fablib` **alongside** TimelineJS3, which means cluttering my `projects` directory.

 I understand that things are the way they are because you haven't completed the setup script for `fablib`, but IMHO, that's not a good enough excuse to clutter my `projects`.  If you'd like, I'd be happy to have a go at adding a `setup.py` and adding `fablib` to `requirements.txt`.

Benny

**Comment by JoeGermuska** [comment]
Benny:

Ah, I see -- we are vague about the specifics of virtual environments, which left a hole in the docs for those unfamiliar. The problem with installing fablib via requirements.txt is that there's an [existing tool](https://pypi.python.org/pypi/fablib) with that name on PyPI -- although we should be able to use `pip`'s [editable packages syntax](https://pip.readthedocs.io/en/1.1/requirements.html#requirements-file-format) 

If you have the time and interest to work on that, we'd appreciate the contribution.

**Comment by scott2b** [comment]
@thehandsomepanther is currently doing work to transition our build process from python/fab based to node/npm based. I want to put off any other build-process related work until that transition is complete

**Comment by daonb** [comment]
@thehandsomepanther may the force be with you!

**Pull request closed without merging**
