### PR TITLE
support raw audio and video files

### PR DESCRIPTION
**Pull request by thehandsomepanther**
create `<audio>` and `<video>` tags for appropriate media elements

questions:
- which file formats do we want to support? some have better browser support than others
- how do we want to handle options like `autoplay` and `controls`?

### CODE REVIEW

**Comment by 03stories** [comment]
As a mac user....mov would be nice, but I think converting to .mp4 has wider support. I'm not sure if this is feasible, but perhaps an open source player like [videojs](http://videojs.com/getting-started/) could be used with default settings. Ability to customize settings would be nice though not necessary initially. 

I'd vote no autoplay, and basic play/pause, scrub, and fullscreen. 

Extra credit: In a dream scenario, since the video media object spans time on the timeline itself, I'd love to be able to select a certain point in the timeline to start the video roughly from that timestamp. Maybe this is more possible (or already happening) with youtube videos.

**Comment by thijstriemstra** [comment]
It would be great to support waveform visualization using https://github.com/katspaugh/wavesurfer.js or https://github.com/collab-project/videojs-wavesurfer.

**Comment by thehandsomepanther** [comment]
Browser testing results

video:

|Browser|`.mp4`?|`.webm`?|`.ogv`?|
|----|----|----|----|
|MS Edge 38|✅|❌|❌|
|IE 11|✅|❌|❌|
|Chrome 57 (Mobile, Android 7)|✅|✅|✅|
|Chrome 57 (Mobile, iOS 10.3.1)|✅|❌|❌|
|Safari (Mobile, iOS 10.3.1)|✅|❌|❌|
|Safari 10.1 (MacOS 10.12)|✅|❌|❌|
|Firefox 50.1 (MacOS 10.12)|✅|✅|✅|
|Chrome 55.0 (MacOS 10.12)|✅|✅|✅|

audio:

|Browser|`.mp3`?|`.wav`?|`.m4a`?|`.ogg`?|`.oga`?|
|----|----|----|----|----|----|
|MS Edge 38|✅|✅|✅|❌|❌|
|IE 11|✅|✅|✅|❌|❌|
|Chrome 57 (Mobile, Android 7)|✅|✅|✅|✅|✅|
|Chrome 57 (Mobile, iOS 10.3.1)|✅|✅|✅|❌|❌|
|Safari (Mobile, iOS 10.3.1)|✅|✅|✅|❌|❌|
|Safari 10.1 (MacOS 10.12)|✅|✅|✅|❌|❌|
|Firefox 50.1 (MacOS 10.12)|✅|✅|✅|✅|❌|
|Chrome 55.0 (MacOS 10.12)|✅|✅|✅|✅|❌|

With this information it looks like we'll be supporting `.mp4` for videos and `.mp3`, `.wav` and `.m4a` for audio tags.

**Comment by scott2b** [comment]
Hm ok. I did not think we had converged on an official set of supported media types. I made this decision in order to push the issue through without ruffling feathers. I figured it is easier to decide on supported types on a case by case basis and add them later in rather than take them out once they've been approved.

imho, adding in filetypes that don't have general cross browser support will open us up to needing to field the related support questions when things don't work as people expect across browsers. For features in general this is the case. Is there precedence here for supporting features only within one or two browsers?

**Comment by paolomazzone** [comment]
It would be great if you should add an icon for .tl-icon-audio inside the icon files.
The code `<span class="tl-icon-audio"></span>` is created but shows nothing.
Is it possible?

**Pull request merged**
