### PR TITLE
Added metadata for FB+Twitter

### PR DESCRIPTION
**Pull request by yawkity**
Used template referenced [here](https://github.com/NUKnightLab/orangeline/issues/58). 

**Questions**
1. Do we want to use the image referenced [here](https://cdn.knightlab.com/libs/purpleline/latest/img/logos/logo_horizontal_691x206_transparent_NOpadding.png) as the image for all the projects?
2. Would the Twitter creator be "knightlab" or "zlwise"

### CODE REVIEW

**Comment by yawkity** [comment]
Once we figure this out I can just do the same for the rest of the projects without submitting a PR

**Comment by scott2b** [comment]
1. Go ahead and use that image. If we want to change we can later
2. knightlab for the twitter

**Comment by scott2b** [comment]
also, I don't know a lot about these tags but this contrib lgtm. Go ahead and merge if you are so inclined

**Comment by JoeGermuska** [comment]
These look pretty good, except that the `{{ title }}` token is not being replaced (or rather it's being replaced with an empty string.)

**Comment by JoeGermuska** [comment]
I find these pages in `website` which derive from `base.html` and thus need to have a `title` configured somehow. I have an idea, but @yawkity maybe you do too... or we can discuss.

```
website/templates/docs/faq.html
website/templates/docs/index.html
website/templates/docs/instantiate-a-timeline.html
website/templates/docs/json-format.html
website/templates/docs/license.html
website/templates/docs/media-types.html
website/templates/docs/options.html
website/templates/docs/overriding-styles.html
website/templates/docs/using-spreadsheets.html
website/templates/error.html
website/templates/index.html
website/templates/test/maps.html
```

**Comment by yawkity** [comment]
Updated it to just be *TimelineJS3*

**Comment by zachwise** [comment]
@yawkity We don't really talk about versions on the site. It should just be called `Timeline JS`

**Comment by zachwise** [comment]
We do have a fairly often referenced twitter handle for Timeline `@TimelineJS` Maybe we should consider having it in the meta.

**Pull request merged**
