### PR TITLE
Update cz.json

### PR DESCRIPTION
**Pull request by lolek**
There was one mistype in my previous contribution. Sorry for that. Sending cz.json without mistype.

### CODE REVIEW

**Comment by JoeGermuska** [comment]
Please make the edits to the primary file, `TimelineJS3/source/js/language/locale/cz.json`

**Comment by lolek** [comment]
I thought i had been doing it.

Lukas


---

Lukáš Bárczay
lolek@lolek.cz

+420 603 233 707
twi: LukasBarczay | fb: facebook.com/lolek
http://www.lolek.cz | http://about.me/lolek

20. 12. 2018 v 19:35, Joe Germuska <notifications@github.com>:

**Comment by JoeGermuska** [comment]
Your previous PR was a change to the correct file. [This one](https://github.com/NUKnightLab/TimelineJS3/pull/595/commits/b349bf9dd346e7c51cfcb2019e8b2d72e64aa7f0), however, is to `TimelineJS3/compiled/js/locale/cz.json`

**Comment by lolek** [comment]
Sorry. I got it. A will put commit to the right file.

**Pull request closed without merging**
