### PR TITLE
Added support to import as npm module (e.g. webpack, browserify)

### PR DESCRIPTION
**Pull request by MPursche**

### CODE REVIEW

**Comment by wangfpp** [comment]
> Thanks, many of us need this feature!
> Just, a newbie question: how can I import as a module? which is the correct sentence to import object (TL?) & library path?

Dou you import success?

**Comment by MPursche** [comment]
Hi,
sorry I just found out I created the pull request against the wrong repository. I initially wanted to create it against my fork of TimelineJS3.
The changes in the pull request do work, but it is not implemented in a good way because a global `TL` object is created.
The module can be used with webpack in the following way:
```javascript
require('timelineJS3');

// global TL object is imported an can directly be used
var timeline = new TL.Timeline(/* ... */);
```
It would be better if `TL` object is returned as a module export. But this would require a lot more refactoring of the code.

Greetings
Marcel

**Comment by wangfpp** [comment]
@MPursche  Hi 
I encountered an error when I configured the language. I can't access the json file under local. Because I don't have a local package locally. How can I solve this? I wish you good luck.

**Comment by JoeGermuska** [comment]
TimelineJS has been [available on npm](https://www.npmjs.com/package/@knight-lab/timelinejs) since v 3.7.0 making this PR obsolete.

**Pull request closed without merging**
