### PR TITLE
Add editorconfig to project root.

### PR DESCRIPTION
**Pull request by bronzehedwick**
Enable automatic editor defaults matching the code style of the project, for those using the plugin. http://editorconfig.org for more information.

### CODE REVIEW

**Comment by scott2b** [comment]
@bronzehedwick it is probably not obvious due to our inconsistent styling in the past, but our official indent style is 4-spaces. It's a work in progress, but you can get a sense of our preferred styles here: https://github.com/NUKnightLab/how-we-work/wiki/Coding-standards

Eventually projects will start conforming to this better, it's just not something we have been able to prioritize yet

**Comment by bronzehedwick** [comment]
@scott2b, thanks for the clarification. Updated to 4 spaces.

**Comment by scott2b** [comment]
I haven't used editorconfig, so I'm not sure, but the indent_style should be space, right?

**Comment by bronzehedwick** [comment]
You're absolutely right, my oversight. Updated.

**Pull request merged**
